apiVersion: apps/v1
kind: Deployment
metadata:
  name: drugmicroservice-deployment
  labels:
    app: DrugMicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DrugMicroservice  
  template:
    metadata:
      labels:
        app: DrugMicroservice
    spec:
      containers:
      - name: drugmicroservice
        image: mailorderpharmacyncr.azurecr.io/drugmicroserviceimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: mailorderpharmacysvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: drugmicroservicesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DrugMicroservice
